"""Demo mode for recording the Pathlight video: simulated café customers, clearly labelled.

Only accounts listed in ``PATHLIGHT_DEMO_ACCOUNTS`` (comma-separated emails; ``local``
allows the local development owner) can use it. For every other account the routes
answer "not found", so the tools do not exist for them.

A simulated customer is an ordinary replay-mode incident marked ``simulated`` with a
``demo-sim-`` run id. Its positions are generated inside the owner's business areas;
no camera saw it. Each position names the camera that would have seen it, so entrance
counts read naturally, and the apps never animate a real camera for simulated people.
One call removes every simulated record without touching real Ring visits.
"""

from __future__ import annotations

import json
import math
import os
import random
import threading
import time
from datetime import datetime, timedelta, timezone

from fastapi import Depends, HTTPException

from . import alerts, analytics
from . import models as m
from .store import audit, dump, event, uid

ENV = "PATHLIGHT_DEMO_ACCOUNTS"
RUN_PREFIX = "demo-sim-"
TITLE = "Simulated customer"
RULE = "Generated by Pathlight demo mode to show a busy café. No camera saw this visit."
EXPLANATION = "Simulated position (Pathlight demo mode); not a camera observation."
ZONE_EXPLANATION = "Business area drawn for the Pathlight demo café by the site owner."

# What each business area is for, from its name.
ROLE_WORDS = {
    "parking": ("parking", "driveway", "car park", "lot"),
    "entrance": ("entrance", "entry", "door"),
    "counter": ("counter", "checkout", "register", "till", "order", "queue"),
    "seating": ("seating", "tables", "dining", "lounge"),
    "window": ("window",),
}
# A small café: visits per day, Monday first, and when they arrive (local hour: weight).
WEEKDAY_VISITS = (42, 44, 46, 49, 58, 72, 61)
HOUR_WEIGHTS = {7: 7, 8: 11, 9: 9, 10: 6, 11: 8, 12: 14, 13: 11, 14: 6, 15: 5, 16: 6, 17: 6, 18: 3}
PREVIOUS_WEEK = 0.82  # the week before is quieter, so this week reads as growth even early in the day
HISTORY_DAYS = 14
SETTLE = timedelta(minutes=10)  # history stops short of now, so it never raises a live alert
WALK_S = (6, 9)
DWELL_S = (11, 14)  # under analytics' 15-second dwell gap

_rushes: dict[str, threading.Event] = {}
_rush_lock = threading.Lock()


# Access ---------------------------------------------------------------------------

def allowed(email: str | None, owner: str | None = None) -> bool:
    listed = {item.strip().lower() for item in os.environ.get(ENV, "").split(",") if item.strip()}
    if owner == "local_owner":
        return "local" in listed
    return bool(email) and email.lower() in listed


def enabled(db, owner: str) -> bool:
    row = db.execute("SELECT email FROM accounts WHERE id=?", (owner,)).fetchone()
    return allowed(row["email"] if row else None, owner)


def require(db, owner: str) -> None:
    if not enabled(db, owner):
        raise HTTPException(404, "Not found")


# Geometry -------------------------------------------------------------------------

def roles(layout: dict) -> dict[str, list[list[tuple[float, float]]]]:
    """Polygons for each role, from the owner's business areas."""
    found: dict[str, list] = {}
    for zone in layout.get("zones", []):
        if zone.get("purpose") != analytics.ANALYTICS_PURPOSE:
            continue
        name = zone["name"].lower()
        role = next((role for role, words in ROLE_WORDS.items() if any(word in name for word in words)), None)
        if role:
            found.setdefault(role, []).append([(float(x), float(y)) for x, y in zone["polygon_xy_m"]])
    return found


def _area(polygon) -> float:
    return abs(sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(polygon, polygon[1:] + polygon[:1]))) / 2


def _point(rng: random.Random, polygons) -> tuple[float, float]:
    # Bigger areas get proportionally more people (the main seating over a small lounge).
    polygon = rng.choices(polygons, weights=[_area(p) or 1e-6 for p in polygons])[0]
    xs, ys = [p[0] for p in polygon], [p[1] for p in polygon]
    for _ in range(200):
        # Stored positions are rounded to centimetres, so test the rounded point.
        x, y = round(rng.uniform(min(xs), max(xs)), 2), round(rng.uniform(min(ys), max(ys)), 2)
        if analytics._inside(x, y, polygon):
            return x, y
    return sum(xs) / len(xs), sum(ys) / len(ys)


def _near(rng: random.Random, spot, polygons, spread=0.2) -> tuple[float, float]:
    """A small shuffle around where someone is standing or sitting, staying in the area."""
    x, y = round(spot[0] + rng.gauss(0, spread), 2), round(spot[1] + rng.gauss(0, spread), 2)
    return (x, y) if any(analytics._inside(x, y, polygon) for polygon in polygons) else spot


def _sees(camera: dict, x: float, y: float) -> bool:
    cx, cy = camera["position_m"][:2]
    distance = math.hypot(x - cx, y - cy)
    if distance > camera.get("range_m", 4):
        return False
    bearing = math.degrees(math.atan2(y - cy, x - cx))
    difference = (bearing - camera.get("heading_degrees", 0) + 540) % 360 - 180
    return abs(difference) <= camera.get("fov_degrees", 70) / 2


def _camera(cameras: list[dict], x: float, y: float) -> str:
    """The camera that would have seen this spot: the nearest one looking at it, else the nearest."""
    distance = lambda c: math.hypot(x - c["position_m"][0], y - c["position_m"][1])
    watching = [c for c in cameras if _sees(c, x, y)]
    return min(watching or cameras, key=distance)["id"]


# Customers ------------------------------------------------------------------------

class _Path:
    def __init__(self, rng: random.Random, start: datetime, areas: dict):
        self.rng, self.t, self.areas, self.samples = rng, start, areas, []

    def walk(self, role: str, steps: int):
        for _ in range(steps if role in self.areas else 0):
            self.samples.append((self.t, *_point(self.rng, self.areas[role])))
            self.t += timedelta(seconds=self.rng.uniform(*WALK_S))

    def stay(self, role: str, seconds: float):
        if role not in self.areas:
            return
        polygons = self.areas[role]
        spot, end = _point(self.rng, polygons), self.t + timedelta(seconds=seconds)
        while self.t < end:
            self.samples.append((self.t, *_near(self.rng, spot, polygons)))
            self.t += timedelta(seconds=self.rng.uniform(*DWELL_S))


def _customer(rng: random.Random, start: datetime, areas: dict, lunch: bool) -> list:
    """One café visit: arrive, order, then leave with a coffee or stay at a table."""
    path = _Path(rng, start, areas)
    path.walk("parking", 2)
    path.walk("entrance", 2)
    wait = 1.5 if lunch else 1.0  # the lunch queue is longer
    kind = rng.random()
    if kind < 0.08:  # looked at the menu and left
        path.stay("counter", rng.uniform(20, 50))
    elif kind < 0.62:  # takeaway
        path.stay("counter", rng.uniform(90, 240) * wait)
    else:  # sat down
        path.stay("counter", rng.uniform(90, 200) * wait)
        if rng.random() < 0.78:
            path.stay("seating", rng.uniform(6, 16) * 60)
        else:
            path.stay("window", rng.uniform(5, 12) * 60)
    path.walk("entrance", 1)
    path.walk("parking", 2)
    return path.samples


def _iso(moment: datetime) -> str:
    return moment.astimezone(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _incident(site: dict, samples: list, created: datetime) -> dict:
    visit = "sim_" + uid("v").split("_", 1)[-1][:12]
    layout = site["layout"]
    floor = layout["floors"][0]["id"]
    cameras = [c for c in layout.get("cameras", []) if c.get("id")]
    observations = [{
        "schema_version": "0.1",
        "observation_id": f"{visit}_{index}",
        "site_id": site["id"],
        "revision_id": site["revision_id"],
        "source_id": _camera(cameras, x, y),
        "observed_at": _iso(at),
        "received_at": _iso(at),
        "category": "person",
        "location": {"kind": "floor_point", "floor_id": floor, "xy_m": [round(x, 2), round(y, 2)],
                     "uncertainty_radius_m": 0.5},
        "evidence": {"mode": "replay"},
        "provenance": {"kind": "inferred", "source_ids": [], "confirmed": False, "explanation": EXPLANATION},
    } for index, (at, x, y) in enumerate(samples)]
    return {
        "id": visit, "site_id": site["id"], "revision_id": site["revision_id"], "calibration_ids": [],
        "run_id": RUN_PREFIX + visit, "status": "reviewed", "title": TITLE, "rule": RULE,
        "started_at": _iso(samples[0][0]), "created_at": _iso(created), "evidence_mode": "replay",
        "observations": observations, "associations": [], "evidence_ids": [],
        "classification_status": "not_requested", "classification": None,
        "reviewed_at": _iso(created), "simulated": True,
    }


def history(site: dict, now: datetime, tz, seed: int = 1) -> list[dict]:
    """Two weeks of café customers ending shortly before now, the same for the same seed."""
    areas = roles(site["layout"])
    if "counter" not in areas or not site["layout"].get("cameras"):
        return []
    rng = random.Random(seed)  # nosec B311 - simulated foot traffic, not security
    today = now.astimezone(tz).date()
    hours, weights = list(HOUR_WEIGHTS), list(HOUR_WEIGHTS.values())
    result = []
    for back in range(HISTORY_DAYS - 1, -1, -1):
        day = today - timedelta(days=back)
        scale = PREVIOUS_WEEK if back >= 7 else 1.0
        count = round(WEEKDAY_VISITS[day.weekday()] * scale * rng.uniform(0.9, 1.1))
        for _ in range(count):
            hour = rng.choices(hours, weights)[0]
            local = datetime(day.year, day.month, day.day, hour, rng.randrange(60), rng.randrange(60), tzinfo=tz)
            start = local.astimezone(timezone.utc)
            samples = _customer(rng, start, areas, lunch=hour in (12, 13))
            if not samples or samples[-1][0] > now - SETTLE:
                continue
            result.append(_incident(site, samples, samples[-1][0]))
    result.sort(key=lambda incident: incident["created_at"])
    return result


def rush_customer(site: dict, rng: random.Random, now: datetime) -> dict | None:
    """Someone who just parked, came in and joined the counter queue."""
    areas = roles(site["layout"])
    if "counter" not in areas:
        return None
    path = _Path(rng, now - timedelta(seconds=64), areas)
    path.walk("parking", 2)
    path.walk("entrance", 2)
    spot = _point(rng, areas["counter"])
    path.t = now - timedelta(seconds=26)
    for _ in range(3):
        path.samples.append((min(path.t, now), *_near(rng, spot, areas["counter"], 0.15)))
        path.t += timedelta(seconds=13)
    return _incident(site, path.samples, now)


# Storage --------------------------------------------------------------------------

def _insert(db, incident: dict) -> None:
    db.execute("INSERT INTO incidents(id, site_id, run_id, data) VALUES (?,?,?,?)",
               (incident["id"], incident["site_id"], incident["run_id"], dump(incident)))


def clear(db, site_id: str) -> int:
    """Remove simulated customers, the alerts they raised and insights written from them."""
    removed = db.execute("DELETE FROM incidents WHERE site_id=? AND run_id LIKE ?",
                         (site_id, RUN_PREFIX + "%")).rowcount
    db.execute("DELETE FROM site_alerts WHERE site_id=? AND simulated=1", (site_id,))
    db.execute("DELETE FROM site_insights WHERE site_id=?", (site_id,))
    return removed


def status(db, site: dict) -> dict:
    simulated = db.execute("SELECT COUNT(*) FROM incidents WHERE site_id=? AND run_id LIKE ?",
                           (site["id"], RUN_PREFIX + "%")).fetchone()[0]
    live = db.execute("SELECT COUNT(*) FROM incidents WHERE site_id=? AND json_extract(data, '$.evidence_mode')='live'",
                      (site["id"],)).fetchone()[0]
    return {"simulated_visits": simulated, "live_visits": live, "rush_active": site["id"] in _rushes,
            "simulated_camera_ids": site.get("simulated_camera_ids", [])}


def _rush(store, site_id: str, customers: int, interval: float, stop: threading.Event) -> None:
    rng = random.Random(time.time_ns())  # nosec B311 - simulated foot traffic, not security
    try:
        for index in range(customers):
            if index and stop.wait(interval):
                break
            with store.connect() as db:
                row = db.execute("SELECT data FROM sites WHERE id=?", (site_id,)).fetchone()
                incident = rush_customer(json.loads(row["data"]), rng, datetime.now(timezone.utc)) if row else None
                if not incident:
                    break
                _insert(db, incident)
                event(db, site_id, "incident.created", incident["id"])
                alerts.try_evaluate(db, site_id)
    finally:
        with _rush_lock:
            if _rushes.get(site_id) is stop:
                del _rushes[site_id]


def start_rush(store, site_id: str, customers: int, interval: float) -> None:
    with _rush_lock:
        if site_id in _rushes:
            raise HTTPException(409, "A lunch rush is already running.")
        stop = _rushes[site_id] = threading.Event()
    if interval <= 0:  # immediate, for tests and quick previews
        _rush(store, site_id, customers, 0, stop)
    else:
        threading.Thread(target=_rush, args=(store, site_id, customers, interval, stop), daemon=True).start()


def stop_rush(site_id: str) -> None:
    with _rush_lock:
        stop = _rushes.pop(site_id, None)
    if stop:
        stop.set()


# Routes ---------------------------------------------------------------------------

def _manual(explanation: str) -> dict:
    return {"kind": "manual", "source_ids": [], "confirmed": True, "explanation": explanation}


def _quiet_passing_zones(db, site: dict) -> None:
    """Only the counter queue alerts in the demo; everyone passes the door and the car park."""
    current = alerts.settings(db, site)
    words = ROLE_WORDS["entrance"] + ROLE_WORDS["parking"]
    limits = {z["name"]: (None if any(w in z["name"].lower() for w in words) else z["limit"]) for z in current["zones"]}
    alerts.save_settings(db, site, current["enabled"], current["window_minutes"], limits)


def install(app, store, principal, owned, geometry_edit, engine):
    @app.get("/v1/demo/sites/{site_id}", response_model=m.DemoStatus)
    def demo_status(site_id: str, p=Depends(principal)):
        with store.connect() as db:
            require(db, p["owner"])
            return status(db, owned(db, site_id, p))

    @app.post("/v1/demo/sites", response_model=m.Site, status_code=201)
    def demo_new_site(body: m.DemoSiteInput, p=Depends(principal)):
        """Create a separate demo place from a drawing and its geometry, published through TwinForge."""
        from .engine import LayoutRejected, create_site, publish_layout, upload_plan
        with store.connect() as db:
            require(db, p["owner"])
        names = [c.name for c in body.cameras]
        if len(set(names)) != len(names):
            raise HTTPException(422, "Give every camera its own name")
        try:
            twin = engine()
            engine_site = create_site(twin, body.name)["id"]
            asset = upload_plan(twin, engine_site, body.name + " floor plan", "image/png", body.drawing_png_base64)["asset_id"]
            floor = "floor_0"
            cameras = [{
                "id": uid("camera"), "name": camera.name, "floor_id": floor, "position_m": list(camera.position_m),
                "heading_degrees": camera.heading_degrees, "pitch_degrees": 0, "fov_degrees": 110,
                "range_m": camera.range_m, "configuration_hash": uid("config"),
                "provenance": _manual("Placed for the Pathlight demo café. Synthetic coordinates; no measured calibration."),
            } for camera in body.cameras]
            xs = [x for room in body.rooms for x, _ in room.polygon_xy_m]
            ys = [y for room in body.rooms for _, y in room.polygon_xy_m]
            (left, right), (front, back) = (min(xs), max(xs)), (min(ys), max(ys))
            source = "Demo café drawing, generated to scale"
            layout = {
                # The demo drawing is generated to an exact scale: its width and depth are the anchors.
                "scale_status": "verified",
                "scale_anchors": [
                    {"points": [[left, front], [right, front]], "distance_m": round(right - left, 3), "source": source},
                    {"points": [[left, front], [left, back]], "distance_m": round(back - front, 3), "source": source},
                ],
                "floors": [{"id": floor, "name": "Ground floor", "elevation_m": 0}],
                "rooms": [{"id": f"room_{index:02d}", "floor_id": floor, "name": room.name, "height_m": 3.0,
                           "polygon_xy_m": [list(point) for point in room.polygon_xy_m],
                           "provenance": _manual("Drawn for the Pathlight demo café.")}
                          for index, room in enumerate(body.rooms, 1)],
                "zones": [{"id": uid("zone"), "floor_id": floor, "name": zone.name, "purpose": analytics.ANALYTICS_PURPOSE,
                           "polygon_xy_m": [list(point) for point in zone.polygon_xy_m], "provenance": _manual(ZONE_EXPLANATION)}
                          for zone in body.zones],
                "portals": [], "cameras": cameras, "asset_ids": [asset],
                "floor_plan": {"asset_id": asset, "origin_xy_m": list(body.drawing_origin_xy_m),
                               "width_m": body.drawing_width_m, "height_m": body.drawing_height_m},
            }
            revision = publish_layout(twin, engine_site, None, layout)
        except LayoutRejected:
            raise HTTPException(422, "TwinForge rejected this café layout.") from None
        except HTTPException:
            raise
        except Exception:
            raise HTTPException(503, "TwinForge is unavailable. Start the engine and retry.") from None
        simulated = [c["id"] for c, spec in zip(cameras, body.cameras) if spec.simulated]
        real = [c["id"] for c, spec in zip(cameras, body.cameras) if not spec.simulated]
        site = {"id": engine_site, "name": body.name, "revision_id": revision["revision_id"],
                "layout": revision["layout"], "monitoring": {"enabled": bool(real), "camera_ids": real},
                "monitoring_version": 0, "evidence_mode": "replay", "ring_status": "not_connected",
                "simulated_camera_ids": simulated}
        with store.connect() as db:
            db.execute("BEGIN IMMEDIATE")
            db.execute("INSERT INTO sites VALUES (?,?,?)", (site["id"], p["owner"], dump(site)))
            db.execute("INSERT OR REPLACE INTO settings VALUES (?,?)", ("active_site:" + p["owner"], site["id"]))
            _quiet_passing_zones(db, site)
            event(db, site["id"], "layout.changed", site["id"])
            audit(db, p["owner"], "demo.site", site["id"])
        return site

    @app.post("/v1/demo/sites/{site_id}/cafe", response_model=m.Site)
    def demo_cafe(site_id: str, body: m.DemoCafeInput, p=Depends(principal)):
        """Draw the café's business areas and mark which map cameras are simulated."""
        with store.connect() as db:
            require(db, p["owner"])
            owned(db, site_id, p)

        def change(layout):
            if not set(body.simulated_camera_ids) <= {c["id"] for c in layout["cameras"]}:
                raise HTTPException(422, "Simulated cameras must be cameras on this map")
            floor = layout["floors"][0]["id"]
            kept = [z for z in layout["zones"] if z.get("purpose") != analytics.ANALYTICS_PURPOSE]
            if len(kept) + len(body.zones) > 30:
                raise HTTPException(422, "A map can hold 30 areas")
            layout["zones"] = kept + [{
                "id": uid("zone"), "floor_id": floor, "name": zone.name.strip(),
                "purpose": analytics.ANALYTICS_PURPOSE,
                "polygon_xy_m": [[round(x, 3), round(y, 3)] for x, y in zone.polygon_xy_m],
                "provenance": {"kind": "manual", "source_ids": [], "confirmed": True, "explanation": ZONE_EXPLANATION},
            } for zone in body.zones]

        geometry_edit(site_id, p, change)
        with store.connect() as db:
            db.execute("BEGIN IMMEDIATE")
            site = owned(db, site_id, p)
            site["simulated_camera_ids"] = list(dict.fromkeys(body.simulated_camera_ids))
            if body.name:
                site["name"] = body.name.strip()
            db.execute("UPDATE sites SET data=? WHERE id=?", (dump(site), site_id))
            _quiet_passing_zones(db, site)
            event(db, site_id, "layout.changed", site_id)
            audit(db, p["owner"], "demo.cafe", site_id)
            return site

    @app.post("/v1/demo/sites/{site_id}/history", response_model=m.DemoStatus)
    def demo_history(site_id: str, body: m.DemoHistoryInput, p=Depends(principal)):
        """Replace the simulated customers with two fresh weeks of them."""
        with store.connect() as db:
            require(db, p["owner"])
            site = owned(db, site_id, p)
        incidents = history(site, datetime.now(timezone.utc), analytics.zone_info(body.tz), body.seed)
        if not incidents:
            raise HTTPException(409, "Draw the café's areas, including a counter, first.")
        stop_rush(site_id)
        with store.connect() as db:
            db.execute("BEGIN IMMEDIATE")
            site = owned(db, site_id, p)
            clear(db, site_id)
            for incident in incidents:
                _insert(db, incident)
            event(db, site_id, "demo.history", site_id)
            audit(db, p["owner"], "demo.history", site_id)
            return status(db, site)

    @app.post("/v1/demo/sites/{site_id}/rush", response_model=m.DemoStatus, status_code=202)
    def demo_rush(site_id: str, body: m.DemoRushInput, p=Depends(principal)):
        """Send simulated customers to the counter now, one every few seconds."""
        with store.connect() as db:
            require(db, p["owner"])
            site = owned(db, site_id, p)
            if "counter" not in roles(site["layout"]):
                raise HTTPException(409, "Draw the café's counter area first.")
            audit(db, p["owner"], "demo.rush", site_id)
        start_rush(store, site_id, body.customers, body.interval_seconds)
        with store.connect() as db:
            return status(db, owned(db, site_id, p))

    @app.delete("/v1/demo/sites/{site_id}/simulated", response_model=m.DemoStatus)
    def demo_clear(site_id: str, p=Depends(principal)):
        """Remove every simulated customer; real Ring visits are untouched."""
        with store.connect() as db:
            require(db, p["owner"])
            owned(db, site_id, p)
        stop_rush(site_id)
        with store.connect() as db:
            db.execute("BEGIN IMMEDIATE")
            site = owned(db, site_id, p)
            clear(db, site_id)
            event(db, site_id, "demo.cleared", site_id)
            audit(db, p["owner"], "demo.cleared", site_id)
            return status(db, site)
